const KEY='ifhamPortfolio_local_v9', DB='ifhamVisualistMedia';
const panel=document.getElementById('panel');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const clone=x=>JSON.parse(JSON.stringify(x));
const DEFAULT={site:{name:'IFHAM KHAN',title:'THE VISUALIST',kicker:'A MULTIDISCIPLINARY VISUAL PRACTICE',description:'A visual practice built around image, movement and detail.',location:'KUPWARA, KASHMIR',experience:'3+ YEARS'},hero:[],folders:[],about:'I am Ifham Khan — a visual creator working across filmmaking, editing, graphic design, color, photography and 3D. This space is a curated look at the work, experiments and visual language behind the projects.',contacts:{email:'ifhamkhan129@gmail.com',phone:'+91 96826 00148',instagram:'@ifham0_ · @ifhamoffilms · @ifhamgfx',youtube:'@ifhamgfx',linkedin:'linkedin.com/in/ifham-khan-52789430b'}};
let data;try{data=JSON.parse(localStorage.getItem(KEY))||DEFAULT}catch(e){data=clone(DEFAULT)}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
const dbp=new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function putFile(blob){const id=crypto.randomUUID();const db=await dbp;await new Promise((res,rej)=>{const q=db.transaction('files','readwrite').objectStore('files').put(blob,id);q.onsuccess=res;q.onerror=()=>rej(q.error)});return 'idb:'+id}
async function getFile(key){if(!key?.startsWith('idb:'))return key;const db=await dbp;return new Promise((res,rej)=>{const q=db.transaction('files').objectStore('files').get(key.slice(4));q.onsuccess=()=>res(q.result?URL.createObjectURL(q.result):'');q.onerror=()=>rej(q.error)})}
async function delFile(key){if(!key?.startsWith('idb:'))return;const db=await dbp;await new Promise((res,rej)=>{const q=db.transaction('files','readwrite').objectStore('files').delete(key.slice(4));q.onsuccess=res;q.onerror=()=>rej(q.error)})}
function field(label,key,val,area=false){return `<div class="field"><label>${label}</label>${area?`<textarea data-key="${key}">${esc(val)}</textarea>`:`<input data-key="${key}" value="${esc(val)}">`}</div>`}
function bindSite(){panel.querySelectorAll('[data-key]').forEach(el=>el.oninput=()=>{data.site[el.dataset.key]=el.value;save()})}
function front(){panel.innerHTML=`<h1 class="title">FRONT 3D</h1><p class="lead">Your reference-style black 3D gallery is the homepage. Replace floating frames, edit the central typography and keep the whole composition editable.</p><div class="card">${field('Name','name',data.site.name)}${field('Creative title','title',data.site.title)}${field('Kicker','kicker',data.site.kicker)}${field('Main description','description',data.site.description,true)}${field('Location','location',data.site.location)}${field('Experience','experience',data.site.experience)}</div><div class="card"><h3>Floating frames</h3><div class="panos">${data.hero.map((p,i)=>`<div class="mini"><img src="${esc(p[0])}" onerror="this.style.display='none'"><input value="${esc(p[0])}" data-hero-url="${i}" placeholder="Image URL"><input value="${esc(p[1])}" data-hero-label="${i}" placeholder="Frame label"><label class="btn dark">REPLACE IMAGE<input hidden type="file" accept="image/*" data-hero-file="${i}"></label><button class="btn danger" data-hero-del="${i}">DELETE</button></div>`).join('')}</div><div class="actions"><button class="btn" id="addFrame">+ ADD FRAME</button></div></div>`;bindSite();panel.querySelectorAll('[data-hero-url]').forEach(e=>e.oninput=()=>{data.hero[+e.dataset.heroUrl][0]=e.value;save()});panel.querySelectorAll('[data-hero-label]').forEach(e=>e.oninput=()=>{data.hero[+e.dataset.heroLabel][1]=e.value;save()});panel.querySelectorAll('[data-hero-file]').forEach(e=>e.onchange=async ev=>{const file=ev.target.files[0];if(!file)return;const i=+e.dataset.heroFile;if(data.hero[i][0]?.startsWith('idb:'))await delFile(data.hero[i][0]);data.hero[i][0]=await putFile(file);save();front()});panel.querySelectorAll('[data-hero-del]').forEach(e=>e.onclick=async()=>{const i=+e.dataset.heroDel;await delFile(data.hero[i][0]);data.hero.splice(i,1);save();front()});document.getElementById('addFrame').onclick=()=>{data.hero.push(['https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80','NEW FRAME']);save();front()})}
function folderForm(folder,i){return `<section class="folder"><div class="folder-head"><h3>${i+1}. ${esc(folder.name)}</h3><div class="actions"><button class="btn" data-up="${i}">↑</button><button class="btn" data-down="${i}">↓</button><button class="btn danger" data-folder-del="${i}">DELETE FOLDER</button></div></div><div class="grid"><div>${field('Folder name','name',folder.name)}${field('Description','desc',folder.desc,true)}</div><div class="upload"><strong>ADD PHOTOS + VIDEOS</strong><p class="note">Select multiple files. Media files are stored in IndexedDB instead of localStorage, so large collections work much better on your computer.</p><label class="btn">CHOOSE FILES<input hidden multiple type="file" accept="image/*,video/*,application/pdf" data-media="${i}"></label></div></div><div class="media">${(folder.items||[]).map((x,j)=>`<div class="media-row"><div><strong>${esc(x.title)}</strong> <small>${x.type}</small></div>${field('Title','title',x.title)}${field('Description','desc',x.desc,true)}<button class="btn danger" data-rm="${i},${j}">DELETE</button></div>`).join('')}</div></section>`}
function folders(){panel.innerHTML=`<h1 class="title">SKILL FOLDERS</h1><p class="lead">Each discipline is an independent full-screen slide. Add unlimited entries in the dashboard; your browser's available storage is the practical limit.</p><div class="actions"><button class="btn" id="newFolder">+ NEW FOLDER</button><button class="btn dark" id="export">EXPORT CONTENT</button><label class="btn dark">IMPORT CONTENT<input hidden type="file" accept="application/json" id="import"></label></div><div id="list"></div>`;draw();document.getElementById('newFolder').onclick=()=>{data.folders.push({id:'folder-'+crypto.randomUUID(),name:'NEW FOLDER',desc:'Add description.',items:[],cls:'s-motion'});save();draw()};document.getElementById('export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='ifham-visualist-content.json';a.click()};document.getElementById('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const incoming=JSON.parse(await file.text());if(confirm('Replace current content with this backup?')){data=incoming;save();draw()}}catch(err){alert('Invalid backup file.')}}}
function draw(){const list=document.getElementById('list');list.innerHTML=data.folders.map(folderForm).join('');list.querySelectorAll('[data-key]').forEach(el=>el.oninput=()=>{const card=el.closest('.folder'),i=[...list.children].indexOf(card);data.folders[i][el.dataset.key]=el.value;save()});list.querySelectorAll('[data-media]').forEach(e=>e.onchange=async ev=>{const i=+e.dataset.media;for(const file of [...ev.target.files]){const key=await putFile(file);data.folders[i].items.push({type:file.type==='application/pdf'?'pdf':file.type.startsWith('video/')?'video':'image',src:key,title:file.name.replace(/\.[^.]+$/,''),desc:''});save()}draw()});list.querySelectorAll('[data-rm]').forEach(e=>e.onclick=async()=>{const [i,j]=e.dataset.rm.split(',').map(Number);await delFile(data.folders[i].items[j].src);data.folders[i].items.splice(j,1);save();draw()});list.querySelectorAll('[data-folder-del]').forEach(e=>e.onclick=async()=>{const i=+e.dataset.folderDel;if(!confirm('Delete this folder and all its media?'))return;for(const x of data.folders[i].items||[])await delFile(x.src);data.folders.splice(i,1);save();draw()});list.querySelectorAll('[data-up]').forEach(e=>e.onclick=()=>{const i=+e.dataset.up;if(i){[data.folders[i-1],data.folders[i]]=[data.folders[i],data.folders[i-1]];save();draw()}});list.querySelectorAll('[data-down]').forEach(e=>e.onclick=()=>{const i=+e.dataset.down;if(i<data.folders.length-1){[data.folders[i+1],data.folders[i]]=[data.folders[i],data.folders[i+1]];save();draw()}})}
function about(){panel.innerHTML=`<h1 class="title">ABOUT</h1><div class="card">${field('About text','about',data.about,true)}</div>`;panel.querySelector('[data-key]').oninput=e=>{data.about=e.value;save()}}
function contact(){panel.innerHTML=`<h1 class="title">CONTACT</h1><div class="card">${Object.entries(data.contacts).map(([k,v])=>field(k,k,v)).join('')}</div>`;panel.querySelectorAll('[data-key]').forEach(e=>e.oninput=()=>{data.contacts[e.dataset.key]=e.value;save()})}
function show(t){({front,folders,about,contact}[t]||front)()}
document.querySelectorAll('aside button').forEach(b=>b.onclick=()=>show(b.dataset.tab));show('front');
